GET http://localhost:3000/version HTTP/1.1

### GENERAR TOKEN
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "user": "admin",
    "password": "123456798"
}

###  OBTENER TODOS USERS
GET http://localhost:3000/users
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

### OBTENER UNO
GET http://localhost:3000/users/fdfd50ca-bdca-4393-8a48-739aa9aa9638
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

### CREAR NUEVO
POST http://localhost:3000/users
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

{
    "alias": "admin",
    "descripcion": "Administrador",
    "password": "123456798",
    "email": "",
    "imagen": "",
    "datos": {},
    "permisos": {
        "users": {
            "ver": true,
            "crear": true,
            "editar": true
        }
    }
}

### EDITAR
PUT http://localhost:3000/users/fdfd50ca-bdca-4393-8a48-739aa9aa9638 HTTP/1.1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

{
    "alias": "admin",
    "descripcion": "Administrador",
    "password": "$2b$10$LbF/N858Fbqxl.APGhaOvOWkelGnC2Fz65CtILChWxOxQ6LRPizZq",    "email": "",
    "imagen": "",
    "datos": {},
    "permisos": {
        "users": {
            "ver": true,
            "crear": true,
            "editar": false
        }
    }
}

### ELIMINAR UNO
DELETE http://localhost:3000/users/c48dd867-a86b-40e7-a04a-2a8e37dc64e5
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48




###  CLIENTES - OBTENER TODOS
GET http://localhost:3000/clientes
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

###  CLIENTE - OBTENER
GET http://localhost:3000/clientes/bf59d0c1-f9d5-48cc-bd67-ce6f329414bb
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

### Crear cliente
POST http://localhost:3000/clientes
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

{
    "cuit" : 20405003644,
    "codigo" : "VAR",
    "razon_social" : "VARGAS SANTIAGO MANUEL",
    "alias" : "SANTY",
    "direccion" : "HIPOLITO IRIGOYEN 900",
    "localidad" : "PAMPA DEL INFIERNO",
    "provincia" : "CHACO",
    "codigo_postal" : "3721",
    "datos" : {},
    "estado" : 1,
    "createdBy" : "2d9c83ce-cc34-46d8-8fe8-b951f2c2b3fe",
    "updatedBy" : "2d9c83ce-cc34-46d8-8fe8-b951f2c2b3fe"
}

### Editar cliente
PUT http://localhost:3000/clientes/c1a9c137-a2c8-44b7-8c89-b022769a04f1
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48

{
    "cuit": 30715327720,
    "codigo": "YAG",
    "razon_social": "YAGUA COLI S.A.",
    "alias": "YAGUA",
    "direccion": "",
    "localidad": "",
    "provincia": "",
    "codigo_postal": "",
    "telefono": "123",
    "correo": "asd@asd.com",
    "datos": {},
    "estado": 1,
    "createdBy": "2d9c83ce-cc34-46d8-8fe8-b951f2c2b3fe",
    "updatedBy": "2d9c83ce-cc34-46d8-8fe8-b951f2c2b3fe"
}


###  OBTENER TODOS USERS
GET http://localhost:3000/articulos/buscar/descripcion/soja
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJzdWIiOiIyZDljODNjZS1jYzM0LTQ2ZDgtOGZlOC1iOTUxZjJjMmIzZmUiLCJkZXNjcmlwY2lvbiI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNvcyI6IntcInVzZXJzXCI6e1widmVyXCI6dHJ1ZSxcImNyZWFyXCI6dHJ1ZSxcImVkaXRhclwiOnRydWV9fSIsImV4cCI6MTcyNTk4NTA3NjE5OSwiaWF0IjoxNzI1OTc3ODc2fQ.mHbx0MXQcOMdqTkT0KCoFYDY1DFjkt3-qEuedqf4L48
